export * from './create.interface'
export * from './find-all.interface'
export * from './find-by-id.interface'
export * from './list-game-rank-by-user.interface'
export * from './list-game-rank.interface'
